name: Compile ESP32 Firmware

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Compile Firmware
        run: pio run

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LilyGo_Gotchi_Firmware
          path: .pio/build/lilygo-t-display-s3/*.bin

      - name: Create ZIP for Release
        # Das -j sorgt dafür, dass keine nervigen Unterordner mit in die ZIP gepackt werden
        run: |
          zip -j LilyGo_Gotchi_Firmware.zip .pio/build/lilygo-t-display-s3/firmware.bin .pio/build/lilygo-t-display-s3/partitions.bin .pio/build/lilygo-t-display-s3/bootloader.bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          # Wir nutzen die interne Lauf-Nummer von GitHub, um automatisch Versionsnummern zu vergeben (z.B. Build #4)
          tag_name: build-${{ github.run_number }}
          name: Firmware Build #${{ github.run_number }}
          body: "🤖 Automatisch kompilierte Firmware. Lade die angehängte ZIP-Datei herunter und flashe die drei `.bin` Dateien über das Adafruit WebSerial ESPTool."
          files: LilyGo_Gotchi_Firmware.zip
